# Generated by Django 4.2.1 on 2023-05-19 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipement',
            name='genre',
            field=models.CharField(choices=[('Ancien', 'Ancien G'), ('Nouveau', 'New G')], max_length=7),
        ),
        migrations.AlterField(
            model_name='equipement',
            name='identifiant',
            field=models.CharField(max_length=20),
        ),
    ]
