# Generated by Django 4.2.1 on 2023-05-19 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipement', '0002_alter_equipement_genre_alter_equipement_identifiant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipement',
            name='identifiant',
        ),
        migrations.AddField(
            model_name='equipement',
            name='identifiant_Pharma',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='equipement',
            name='numero_serie',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='equipement',
            name='modele_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
