# Generated by Django 4.2.1 on 2023-05-19 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipement', '0003_remove_equipement_identifiant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='equipement_images/'),
        ),
    ]
