# Generated by Django 4.2.1 on 2023-05-19 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipement', '0004_equipement_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageEquipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='equipement_images/')),
                ('equipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='equipement.equipement')),
            ],
        ),
    ]
