# Generated by Django 4.2.1 on 2023-05-19 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipement', '0005_imageequipement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipement',
            name='image',
        ),
    ]
