# Generated by Django 4.2.1 on 2023-05-19 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipement', '0006_remove_equipement_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipement',
            old_name='nom',
            new_name='Appareil',
        ),
        migrations.RenameField(
            model_name='equipement',
            old_name='modele_type',
            new_name='Autres',
        ),
        migrations.RenameField(
            model_name='equipement',
            old_name='identifiant_Pharma',
            new_name='Code_machine',
        ),
        migrations.RemoveField(
            model_name='equipement',
            name='active',
        ),
        migrations.RemoveField(
            model_name='equipement',
            name='date_visite_T',
        ),
        migrations.RemoveField(
            model_name='equipement',
            name='genre',
        ),
        migrations.AddField(
            model_name='equipement',
            name='Connecte_AD',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipement',
            name='Connecte_reseau',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipement',
            name='DOC_qualification',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipement',
            name='Documentation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipement',
            name='Emplacement',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipement',
            name='Etat',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipement',
            name='Etat_materiel_informatique',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipement',
            name='Fournisseur',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipement',
            name='Logiciel',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipement',
            name='Maintenance',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipement',
            name='Password',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='equipement',
            name='QX',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='equipement',
            name='Sauvegarde',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipement',
            name='Situation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipement',
            name='Version_windows',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipement',
            name='connecté_imprimante',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='equipement',
            name='date_installation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipement',
            name='matrcie_acces',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipement',
            name='modele',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipement',
            name='planning_sauvegarde',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipement',
            name='version_logiciel',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='equipement',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
