# Generated by Django 4.2.1 on 2023-05-29 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipement', '0007_rename_nom_equipement_appareil_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Num', models.IntegerField()),
                ('Emplacement', models.CharField(max_length=100, null=True)),
                ('Appareil', models.CharField(max_length=100)),
                ('Etat', models.CharField(max_length=100, null=True)),
                ('modele', models.CharField(max_length=100, null=True)),
                ('Code_machine', models.CharField(max_length=20, null=True)),
                ('Password', models.CharField(max_length=20, null=True)),
                ('matrcie_acces', models.CharField(max_length=100, null=True)),
                ('Sauvegarde', models.CharField(max_length=100, null=True)),
                ('Connecte_reseau', models.CharField(max_length=100, null=True)),
                ('Connecte_AD', models.CharField(max_length=100, null=True)),
                ('connecté_imprimante', models.CharField(max_length=10, null=True)),
                ('Maintenance', models.CharField(max_length=100, null=True)),
                ('planning_sauvegarde', models.CharField(max_length=100, null=True)),
                ('Logiciel', models.CharField(max_length=100, null=True)),
                ('version_logiciel', models.CharField(max_length=100, null=True)),
                ('date_installation', models.CharField(max_length=100, null=True)),
                ('Version_windows', models.CharField(max_length=100, null=True)),
                ('Situation', models.CharField(max_length=100, null=True)),
                ('Fournisseur', models.CharField(max_length=100, null=True)),
                ('Etat_materiel_informatique', models.CharField(max_length=100, null=True)),
                ('numero_serie', models.CharField(max_length=40, null=True)),
                ('Documentation', models.CharField(max_length=100, null=True)),
                ('DOC_qualification', models.CharField(max_length=100, null=True)),
                ('QX', models.CharField(max_length=10, null=True)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('site_officiel', models.URLField(blank=True, null=True)),
                ('Autres', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageEquipements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='equipement_images/')),
                ('equipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='equipement.equipements')),
            ],
        ),
        migrations.RemoveField(
            model_name='imageequipement',
            name='equipement',
        ),
        migrations.DeleteModel(
            name='Equipement',
        ),
        migrations.DeleteModel(
            name='ImageEquipement',
        ),
    ]
