# Generated by Django 4.2.1 on 2023-06-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipement', '0008_equipements_imageequipements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageequipements',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='membre/static/equipement_pdfs/'),
        ),
        migrations.AlterField(
            model_name='imageequipements',
            name='image',
            field=models.ImageField(upload_to='membre/static/equipement_images/'),
        ),
    ]
