# Generated by Django 4.2.1 on 2023-06-13 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipement', '0009_imageequipements_pdf_alter_imageequipements_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageequipements',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='imageequipements',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='fichiers/'),
        ),
    ]
