# Generated by Django 4.2.1 on 2023-07-03 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipement', '0010_alter_imageequipements_image_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImageEquipements',
            new_name='DocEquipement',
        ),
        migrations.RenameModel(
            old_name='Equipements',
            new_name='Equipement',
        ),
    ]
