# Generated by Django 4.2.1 on 2023-07-03 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipement', '0011_rename_imageequipements_docequipement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipement',
            name='QX',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
