# Generated by Django 4.2.1 on 2023-07-06 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipement', '0012_alter_equipement_qx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=100, null=True)),
                ('Nom', models.CharField(max_length=100, null=True)),
                ('Prenom', models.CharField(max_length=100, null=True)),
                ('Role', models.CharField(max_length=200, null=True)),
                ('Situation', models.CharField(choices=[('actif', 'Actif'), ('Inactif', 'Inactive')], max_length=20)),
                ('equipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matrice', to='equipement.equipement')),
            ],
        ),
    ]
