# Generated by Django 4.2.1 on 2024-05-08 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipement', '0013_matrice'),
    ]

    operations = [
        migrations.AddField(
            model_name='matrice',
            name='date_modfication',
            field=models.DateField(auto_now=True),
        ),
    ]
