# Generated by Django 4.2.1 on 2023-05-14 22:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('HPLC', 'Hplc'), ('Balance', 'Balance'), ('PC', 'Pc')], max_length=7)),
                ('description', models.CharField(max_length=1000)),
                ('date_visite_T', models.IntegerField(validators=[django.core.validators.MinValueValidator(1901), django.core.validators.MaxValueValidator(2023)])),
                ('active', models.BooleanField(default=True)),
                ('site_officiel', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
