# Generated by Django 4.2.1 on 2023-05-17 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Equipement',
        ),
    ]
