# Generated by Django 4.2.1 on 2024-05-05 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membre', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analyste',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
            ],
        ),
    ]
